# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"dotfiles" = "âš™ï¸"
"helix" = "ğŸ§¬"
"zellij" = "ğŸ§‘â€ğŸ’»"
"alacritty" = "ğŸ’»"
"github" = "ï„“"
"rust" = "î¨"
"google" = "ï† "
"private browsing" = "ïˆ›"
"firefox" = "ğŸ¦Š"
"chrome" = "ï‰¨"
"thunderbird" = "âœ‰ï¸"
"thunar" = "î—¾"
"file manager" = "ï¼"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"nvim" = "îŸ…"
"gthumb" = "ï€¾"
"menu" = "ï¡œ"
"calculator" = "ï—«"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"mpv" = "ïœª"
"music" = "ï€"
"disk usage" = "ïŸ‰"
".pdf" = "ïœ¤"
"aseprite" = "ğŸ–Œ"

[other]
fallback_icon = "?"
deduplicate_icons = false
