# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"kdash" = "â˜ï¸"
"keepass" = "ğŸ”‘"
"dotfiles" = "âš™ï¸"
"helix" = "ğŸ§¬"
"zellij" = "ğŸ§‘â€ğŸ’»"
"alacritty" = "ğŸ’»"
"element" = "ğŸ’¬"
"firefox" = "ğŸ¦Š"
"thunderbird" = "ğŸ“¬"
"thunar" = "ğŸ“‚"
"transmission" = "ğŸ“¥"
"aseprite" = "ğŸ–Œ"
"tuxguitar" = "ğŸ¸"
"bosca" = "ğŸ‘¾"
"wine" = "ğŸ·"

[other]
fallback_icon = "ğŸ¤·"
deduplicate_icons = false
